
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy
  annotations:
    description: Node Hello
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-hello
  template:
    metadata:
      name: node-hello
      labels:
        env: dev
        name: node-hello
    spec:
      containers:
        - name: node-hello
          image: "node-hello"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: node-hello
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: node-hello
  type: NodePort
